services:
  kernel:
    image: "kmops-cache:latest"
    hostname: kernel
    container_name: kernel
    ports:
      - "5900:5900"
    command: qemu-system-x86_64 -vnc 0.0.0.0:0 -drive format=raw,file=target/x86_64-os/debug/bootimage-kmops.bin
  novnc:
    hostname: novnc
    container_name: novnc
    build:
      dockerfile: Dockerfile.novnc
    ports:
      - "6080:6080"
    depends_on:
      - kernel
