FROM alpine:latest

WORKDIR /app

ENV VERSION_NOVNC="v1.5.0"

COPY novnc_entrypoint.sh .

RUN apk --no-cache --update --upgrade add \
        bash \
        python3 \
        python3-dev \
        py-pip \
        build-base \
        git \
        bind-tools

RUN git clone https://github.com/novnc/noVNC --branch ${VERSION_NOVNC} /app/noVNC

ENTRYPOINT ["/app/novnc_entrypoint.sh"]
