[tasks.run_qemu]
command = "qemu-system-x86_64"
args = ["-drive", "format=raw,file=out/bootimage-kmops.bin"]

#---------- Native tasks ----------
[tasks.install_bootimage]
command = "cargo"
args = ["install", "bootimage"]

[tasks.install_build_dependencies]
dependencies = ["install_bootimage"]

[tasks.build]
command = "cargo"
args = ["bootimage"]
dependencies = ["install_build_dependencies"]

#---------- Docker tasks ----------
[tasks.build_docker_cache_image]
script = "docker build --platform linux/amd64 -t kmops-cache:latest -f Dockerfile.cache ."

[tasks.build_docker]
script = "docker build --no-cache --output type=local,dest=out -t kmops:latest -f Dockerfile ."
