[tasks.run]
command = "cargo"
args = ["run"]

[tasks.install_rust_src]
command = "rustup"
args = ["component", "add", "rust-src"]

[tasks.install_bootimage]
command = "cargo"
args = ["install", "bootimage"]

[tasks.install_llvm_tools_preview]
command = "cargo"
args = ["component", "add", "llvm-tools-preview"]

[tasks.build]
command = "cargo"
args = ["build"]
dependencies = ["install_rust_src", "install_llvm_tools_preview", "install_bootimage"]
