[tasks.run]
command = "cargo"
args = ["run"]

[tasks.build_dependencies]
command = "rustup"
args = ["component", "add", "rust-src"]

[tasks.build]
command = "cargo"
args = ["build"]
dependencies = ["build_dependencies"]
