#---------- Native tasks ----------
[tasks.install_bootimage]
command = "cargo"
args = ["install", "bootimage"]

[tasks.build]
command = "cargo"
args = ["bootimage"]
dependencies = ["install_bootimage"]

#---------- Docker tasks ----------
[tasks.build_docker_cache_image]
script = "docker build --platform linux/amd64 -t kmops-cache:latest -f Dockerfile.cache ."

[tasks.build_docker]
script = "docker build --no-cache --output type=local,dest=out -t kmops:latest -f Dockerfile ."
dependencies = ["remove_out_dir", "make_out_dir"]

[tasks.make_out_dir]
script_runner = "@shell"
script = "mkdir -p out"

[tasks.remove_out_dir]
script_runner = "@shell"
script = "rm -rf out"
